name: Deploy to EC2

on:
  push:
    branches: [master, mock-server]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }} # Add public key to EC2 instance before running the action
          script: |
            if [ ! -d "node-swagger" ]; then
              git clone https://github.com/nivek-yang/node-swagger.git
              cd node-swagger
            else
              cd node-swagger
              git pull
            fi
            docker-compose up -d
            # sleep 3600 # Wait for 1 hour
            # doccker-compose down
            # docker rmi $(docker images -q)
